name: Deploy Spring Boot App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH & Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: 13.53.75.88
          username: ubuntu
          key: ${{ secrets.PMF }}
          script: |
            # Trap SIGTERM so the step can exit 0 instead of 143
            trap 'echo "Caught SIGTERM, exiting OK"; exit 0' TERM

            # Set environment variables
            export SPRING_PROFILES_ACTIVE=global
            export TRELLO_DB_PASSWORD=${{ secrets.TRELLO_DB_PASSWORD }}
            export MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}

            # Navigate to the app directory or clone the repository
            mkdir -p ~/app && cd ~/app
            if [ -d .git ]; then
              git pull origin main
            else
              git clone https://github.com/Pahlavonmuhammad/trello.git .
            fi

            # Ensure mvnw is executable
            if [ -f "./mvnw" ]; then
              chmod +x mvnw
            else
              echo "mvnw file not found, exiting."
              exit 1
            fi

            # Build the application
            ./mvnw clean package -DskipTests

            # Restart the Java app detached
            pkill -f 'java' || true
            nohup java -jar target/*.jar > app.log 2>&1 &

            # Exit cleanly
            exit 0
