name: Deploy Spring Boot App

on:
  push:
    branches:
      - main  # You can change this to another branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH & Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: 13.53.75.88
          username: ubuntu
          key: ${{ secrets.PMF }}
          script: |
            # Set environment variables
            export SPRING_PROFILES_ACTIVE=global
            export TRELLO_DB_PASSWORD=${{ secrets.TRELLO_DB_PASSWORD }}
            export MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}

            # Navigate to the app directory or clone the repository
            mkdir -p ~/app && cd ~/app
            if [ -d .git ]; then
              git pull origin main
            else
              git clone https://github.com/Pahlavonmuhammad/trello.git . 
            fi

            # Check if mvnw file exists and set execute permissions
            if [ -f "./mvnw" ]; then
              chmod +x mvnw
            else
              echo "mvnw file not found, exiting."
              exit 1
            fi

            # Build the application with Maven
            ./mvnw clean package -DskipTests

            # Terminate any running Java processes and restart the app, detached from the session
            pkill -f 'java' || true
            setsid java -jar target/*.jar > app.log 2>&1 < /dev/null &

            # Signal success so GitHub Actions doesn’t treat the backgrounded script as a failure
            exit 0
